import json
import os

adm_data = {
    'title': 'Accounting for Decision Making',
    'badge': 'Professional Certificate',
    'duration': '9 weeks',
    'effort': '3 - 4 hrs/week',
    'overview': 'In any given organisation, the information generated by accounting systems is of paramount importance to both internal and external stakeholders. The IIMBx MOOC on Accounting for Decision Making is designed for graduates, entry-level managers, and personnel already serving in managerial positions to provide them with the necessary foundational knowledge in Accounting. You will learn to read and understand financial statements as well as develop the capability to analyse business performance through financial statements.',
    'audience': 'Executives, Students pursuing post graduate and people who are aspiring to develop their skills in the field of managerial accounting.',
    'instructor_name': 'Prof. M S Narasimhan',
    'instructor_role': 'Finance and Accounting',
    'outcomes': [
        'Read and explain the contents of financial statements',
        'Analyse the financial statements',
        'Prepare operational and financial budgets',
        'Apply accounting information to plan and control your business and make decisions'
    ],
    'modules': [
        {'title': 'Week 1 - Mechanics of Financial Accounting', 'desc': 'Fundamental Accounting Terms, Recording Accounting Transactions, Financial Statements, Financial Accounting Regulations, Annual Report.'},
        {'title': 'Week 2 - Reading Financial Statements', 'desc': 'Balance Sheet – Shareholders Fund, Liabilities, Assets. Income Statement – Revenue, Expenses and Profit. Cash Flow Statement.'},
        {'title': 'Week 3 - Financial Statement Analysis', 'desc': 'Assessing Financial Health, Asset Management, Cost Management, Leverage Management, Risk Management, Benchmarking.'},
        {'title': 'Week 4 - Product Costing', 'desc': 'Methods of Product Costing, Job Costing, Customer Costing, Process Costing, Indirect Cost and Allocation, Misallocation of Indirect Cost, Activity Based Costing.'},
        {'title': 'Week 5 - Cost Analysis for Decision Making', 'desc': 'Absorption vs. Marginal Costing, Behavior of Costs, Break-even Analysis, Pricing Decision, Make or Buy decision.'},
        {'title': 'Week 6 - Budgeting and Variance Analysis', 'desc': 'Strategic Planning and Budgets, Budgeting Process, Preparation of Master Budget, Setting Standards, Variance Analysis.'},
        {'title': 'Week 7 - Financial Markets', 'desc': 'Introduction, Financial System, Institutional Financing, Direct Capital Flow, Financial Instruments, Role of Finance Function.'},
        {'title': 'Week 8 - Capital Budgeting', 'desc': 'Time Value of Money, Capital Budgeting Techniques, Estimation of Project Cash Flows, Capital Structure and Cost of Capital, Special Issues in Capital Budgeting.'},
        {'title': 'Week 9 - Working Capital Management', 'desc': 'Short-term Financial Planning, Working Capital Cycle, Financing of Working Capital, Inventory Management, Receivables Management, Cash Management, Managing Payables.'}
    ]
}

def generate_variant(variant_type, filename):
    # variant_type: 1 (Baseline), 2 (Dark Mode), 3 (Compact)
    
    # CSS overrides based on variant
    bg_color = "var(--parchment)"
    text_color = "var(--charcoal)"
    hero_bg = "var(--charcoal)"
    hero_text = "var(--parchment)"
    warning_banner = ""
    accordion_script = ""
    
    if variant_type == 2:
        bg_color = "var(--navy)"
        text_color = "var(--parchment)"
        hero_bg = "var(--navy)"
        warning_banner = """
        <div style="background-color: var(--crimson); color: white; padding: 10px; text-align: center; font-family: 'IBM Plex Mono', monospace; font-size: 12px; font-weight: bold; position: sticky; top: 0; z-index: 9999;">
            ⚠ BEYOND BRAND COMPLIANCE - EXCEEDS 70/15/15 COLOR RULE FOR DARK MODE IMPACT ⚠
        </div>
        """
        
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{adm_data['title']} | IIMBx</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&family=Source+Serif+4:opsz,wght@8..60,400;8..60,600&display=swap" rel="stylesheet">
    <style>
        :root {{
            --parchment: #F4EFE3;
            --charcoal: #1A1B1E;
            --marigold: #C97138;
            --crimson: #AE2C2A;
            --navy: #172D6B;
            --font-display: 'Source Serif 4', serif;
            --font-body: 'Inter', sans-serif;
            --font-mono: 'IBM Plex Mono', monospace;
        }}
        body {{
            font-family: var(--font-body);
            background-color: {bg_color};
            color: {text_color};
            margin: 0;
            padding: 0;
            line-height: 1.6;
            -webkit-font-smoothing: antialiased;
        }}
        h1, h2, h3 {{
            font-family: var(--font-display);
            font-weight: 600;
            margin: 0 0 1rem 0;
        }}
        .eyebrow {{
            font-family: var(--font-mono);
            color: var(--marigold);
            font-size: 0.875rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            margin-bottom: 0.5rem;
            display: block;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 2rem;
        }}
        
        /* Hero Section */
        .hero {{
            background-color: {hero_bg};
            color: {hero_text};
            padding: 6rem 0;
            position: relative;
        }}
        .hero h1 {{
            font-size: 3.5rem;
            line-height: 1.1;
            margin-bottom: 1.5rem;
            max-width: 800px;
        }}
        .hero-meta {{
            display: flex;
            gap: 2rem;
            margin-bottom: 2rem;
            font-family: var(--font-mono);
            font-size: 0.875rem;
        }}
        .badge {{
            background-color: var(--marigold);
            color: white;
            padding: 0.25rem 0.75rem;
            border-radius: 999px;
            display: inline-block;
            margin-bottom: 1rem;
        }}
        .btn {{
            background-color: var(--marigold);
            color: white;
            border: none;
            padding: 1rem 2rem;
            font-family: var(--font-body);
            font-weight: 600;
            font-size: 1rem;
            cursor: pointer;
            transition: opacity 0.2s;
            text-decoration: none;
            display: inline-block;
        }}
        .btn:hover {{
            opacity: 0.9;
        }}
        
        /* Sections */
        section {{
            padding: 5rem 0;
        }}
        section h2 {{
            font-size: 2.5rem;
            margin-bottom: 2rem;
        }}
        
        /* Grid Layouts */
        .grid-2 {{
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 4rem;
        }}
        .grid-3 {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 2rem;
        }}
        
        /* Cards */
        .card {{
            background: {"rgba(255,255,255,0.05)" if variant_type == 2 else "white"};
            padding: 2rem;
            border-radius: 8px;
            border-top: 4px solid var(--marigold);
            box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        }}
        
        /* Modules */
        .module-list {{
            list-style: none;
            padding: 0;
            margin: 0;
        }}
"""
    if variant_type == 3: # Accordion for compact
        html += """
        .module-item {
            border-bottom: 1px solid rgba(0,0,0,0.1);
        }
        .module-header {
            padding: 1.5rem 0;
            cursor: pointer;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .module-header h3 {
            margin: 0;
            font-size: 1.25rem;
            font-family: var(--font-body);
        }
        .module-content {
            display: none;
            padding-bottom: 1.5rem;
            color: #666;
        }
        .module-item.active .module-content {
            display: block;
        }
        """
        accordion_script = """
        <script>
            document.querySelectorAll('.module-header').forEach(header => {
                header.addEventListener('click', () => {
                    header.parentElement.classList.toggle('active');
                });
            });
        </script>
        """
    else:
        html += """
        .module-item {
            padding: 2rem 0;
            border-bottom: 1px solid rgba(0,0,0,0.1);
        }
        .module-item h3 {
            font-size: 1.25rem;
            font-family: var(--font-body);
            margin-bottom: 0.5rem;
        }
        """
        if variant_type == 2:
            html = html.replace('rgba(0,0,0,0.1)', 'rgba(255,255,255,0.1)')

    html += f"""
    </style>
</head>
<body>
    {warning_banner}
    <nav style="padding: 1rem 0; background: var(--charcoal); color: white;">
        <div class="container">
            <span style="font-family: var(--font-display); font-weight: 600; font-size: 1.5rem;">IIMBx</span>
        </div>
    </nav>

    <header class="hero">
        <div class="container">
            <span class="badge">{adm_data['badge']}</span>
            <h1>{adm_data['title']}</h1>
            <div class="hero-meta">
                <div>⏱ {adm_data['duration']}</div>
                <div>⚡ {adm_data['effort']}</div>
            </div>
            <a href="#apply" class="btn">Apply Now</a>
            <p style="margin-top: 2rem; font-style: italic; font-family: var(--font-display);">"The same faculty. Wherever you are."</p>
        </div>
    </header>

    <section>
        <div class="container grid-2">
            <div>
                <span class="eyebrow">Overview</span>
                <h2>Master Managerial Accounting</h2>
                <p>{adm_data['overview']}</p>
            </div>
            <div class="card">
                <span class="eyebrow">Target Audience</span>
                <p>{adm_data['audience']}</p>
                <div style="margin-top: 2rem;">
                    <span class="eyebrow">Instructor</span>
                    <h3 style="font-family: var(--font-body); margin-bottom: 0.25rem;">{adm_data['instructor_name']}</h3>
                    <p style="margin: 0; font-size: 0.875rem;">{adm_data['instructor_role']}</p>
                </div>
            </div>
        </div>
    </section>

    <section style="background-color: {"rgba(255,255,255,0.02)" if variant_type == 2 else "white"};">
        <div class="container">
            <span class="eyebrow">Learning Outcomes</span>
            <h2>What You Will Learn</h2>
            <div class="grid-3">
"""
    for outcome in adm_data['outcomes']:
        html += f"""
                <div style="padding-left: 1rem; border-left: 2px solid var(--marigold);">
                    <p style="margin: 0;">{outcome}</p>
                </div>
        """
    html += f"""
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <span class="eyebrow">Curriculum</span>
            <h2>Program Structure</h2>
            <div style="max-width: 800px;">
                <ul class="module-list">
"""
    for module in adm_data['modules']:
        if variant_type == 3:
            html += f"""
                    <li class="module-item">
                        <div class="module-header">
                            <h3>{module['title']}</h3>
                            <span>+</span>
                        </div>
                        <div class="module-content">
                            <p>{module['desc']}</p>
                        </div>
                    </li>
            """
        else:
            html += f"""
                    <li class="module-item">
                        <h3>{module['title']}</h3>
                        <p style="margin: 0;">{module['desc']}</p>
                    </li>
            """
            
    html += f"""
                </ul>
            </div>
        </div>
    </section>

    <footer style="background: var(--charcoal); color: var(--parchment); padding: 4rem 0;">
        <div class="container" style="text-align: center;">
            <p>© 2026 IIMBx. All rights reserved.</p>
        </div>
    </footer>
    {accordion_script}
</body>
</html>
"""
    
    with open(f"prototypes/{filename}", 'w', encoding='utf-8') as f:
        f.write(html)
        
    print(f"Generated prototypes/{filename}")

generate_variant(1, 'adm_v1_variant_1.html')
generate_variant(2, 'adm_v1_variant_2.html')
generate_variant(3, 'adm_v1_variant_3.html')
