document.addEventListener('DOMContentLoaded', () => {
  const grid = document.getElementById('programme-grid');
  const modal = document.getElementById('audit-modal');
  const modalBody = document.getElementById('modal-body');
  const closeBtn = document.getElementById('close-modal');

  // Load data from global window object (avoids CORS issues on file:// protocol)
  if (window.AUDIT_DATA) {
    window.AUDIT_DATA.forEach(data => {
      renderCard(data, grid);
    });
  } else {
    console.error('No audit data found in window.AUDIT_DATA');
  }

  function getScoreClass(score) {
    if (score >= 90) return 'high';
    if (score >= 70) return 'med';
    return 'low';
  }

  function renderCard(data, container) {
    const card = document.createElement('div');
    card.className = 'card';
    card.innerHTML = `
      <h2>${data.programmeName}</h2>
      <div class="card-meta">File: ${data.file} | Last Audited: ${new Date(data.auditDate).toLocaleDateString()}</div>
      <div class="scores">
        <div class="score">
          <span class="score-label">Brand</span>
          <span class="score-val ${getScoreClass(data.scores.brand)}">${data.scores.brand}%</span>
        </div>
        <div class="score">
          <span class="score-label">Content</span>
          <span class="score-val ${getScoreClass(data.scores.content)}">${data.scores.content}%</span>
        </div>
        <div class="score">
          <span class="score-label">UX</span>
          <span class="score-val ${getScoreClass(data.scores.ux)}">${data.scores.ux}%</span>
        </div>
      </div>
      <div style="font-size: 11px; color: #888; margin-top: -12px; margin-bottom: 20px; font-style: italic;">
        % indicates readiness for launch (100 = Perfect, <90 = Needs Review).
      </div>
      <div style="font-size: 13px; color: #444;">${data.summary}</div>
    `;
    card.addEventListener('click', () => openModal(data));
    container.appendChild(card);
  }

  function openModal(data) {
    let gapsHtml = '';
    data.contentGaps.forEach(g => {
      gapsHtml += `
        <tr>
          <td style="padding: 8px; border-bottom: 1px solid #eee;">${g.section}</td>
          <td style="padding: 8px; border-bottom: 1px solid #eee;">${g.oldContent}</td>
          <td style="padding: 8px; border-bottom: 1px solid #eee;">${g.newContent}</td>
          <td style="padding: 8px; border-bottom: 1px solid #eee; display: flex; align-items: center;">
            ${g.verdict}
            ${g.explanation ? `<span class="info-trigger" style="margin-left: 6px;">i<span class="tooltip" style="bottom: 120%; width: 220px; z-index: 1000;"><strong>Swarm Context:</strong><br>${g.explanation}</span></span>` : ''}
          </td>
        </tr>
      `;
    });

    let wireframesHtml = '';
    data.wireframes.forEach(w => {
      wireframesHtml += `
        <div class="section-diff">
          <div class="panel">
            <h4>
              <span>Old Live Website</span>
              <span class="info-trigger">i
                <span class="tooltip">
                  <strong>Old Live Site</strong><br>
                  • <strong>Source:</strong> Crawled from the active live IIMBx website.<br>
                  • <strong>Idea:</strong> Original institutional site design.
                </span>
              </span>
            </h4>
            <pre>${w.oldLive || '(Not Captured)'}</pre>
          </div>
          <div class="panel">
            <h4>
              <span>Current Layout (HTML Prototype)</span>
              <span class="info-trigger">i
                <span class="tooltip">
                  <strong>Current HTML Prototype</strong><br>
                  • <strong>Source:</strong> HTML file supplied by the design/marketing team.<br>
                  • <strong>Idea:</strong> Design agency / marketing team's layout proposal.
                </span>
              </span>
            </h4>
            <pre>${w.current}</pre>
          </div>
          <div class="panel">
            <h4>
              <span>Proposed UX (Swarm Intelligence)</span>
              <span class="info-trigger">i
                <span class="tooltip">
                  <strong>Swarm Optimized Layout</strong><br>
                  • <strong>Source:</strong> Generated by the Swarm AI (Agents 09 & 10).<br>
                  • <strong>Idea:</strong> Applied UX patterns (tabs, accordions) to hit target scroll depth.
                </span>
              </span>
            </h4>
            <pre>${w.proposed}</pre>
          </div>
        </div>
      `;
    });

    let brandHtml = '';
    if (data.brandChecks) {
      data.brandChecks.forEach(b => {
        brandHtml += `
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${b.rule}</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-family: monospace;">${b.expected}</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-family: monospace;">${b.actual}</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${b.status}</td>
          </tr>
        `;
      });
    }

    modalBody.innerHTML = `
      <h2>${data.programmeName} Audit Report</h2>
      <div style="background: #fbf8f1; padding: 16px; border: 1px solid #eee; border-left: 4px solid var(--accent); border-radius: 6px; margin: 20px 0;">
        <p style="margin: 0 0 8px 0; font-size: 14px; line-height: 1.5;">
          <strong>What is this page?</strong> The link below opens <code>${data.file}</code>. This is the <strong>HTML Prototype</strong> proposed by the marketing team.
        </p>
        <p style="margin: 0 0 16px 0; font-size: 14px; line-height: 1.5;">
          <strong>Brand Status:</strong> This prototype scored <strong>${data.scores.brand}%</strong> for brand compliance. ${data.scores.brand === 100 ? 'It perfectly follows the May 2026 Brand Playbook (correct colors, typography, and voice).' : 'It contains brand violations (e.g. banned colors or fonts) that need fixing.'}
        </p>
        <a href="../${data.file}" target="_blank" style="display: inline-flex; align-items: center; gap: 8px; background: var(--text); color: #fff; padding: 8px 16px; border-radius: 4px; font-weight: 500; font-size: 13px; text-decoration: none; transition: background 0.2s;" onmouseover="this.style.background='var(--accent)'" onmouseout="this.style.background='var(--text)'">
          Open HTML Prototype in Browser &rarr;
        </a>
      </div>
      
      <h3 style="margin-top:30px; border-bottom: 2px solid #eee; padding-bottom: 8px;">Brand Guideline Compliance</h3>
      <table style="width:100%; border-collapse: collapse; text-align: left; font-size: 14px;">
        <thead>
          <tr>
            <th style="padding: 8px; border-bottom: 2px solid #ccc;">Rule</th>
            <th style="padding: 8px; border-bottom: 2px solid #ccc;">Required by Playbook</th>
            <th style="padding: 8px; border-bottom: 2px solid #ccc;">Found in Prototype</th>
            <th style="padding: 8px; border-bottom: 2px solid #ccc;">Status</th>
          </tr>
        </thead>
        <tbody>
          ${brandHtml}
        </tbody>
      </table>

      <h3 style="margin-top:30px; border-bottom: 2px solid #eee; padding-bottom: 8px;">Content Gaps</h3>
      <table style="width:100%; border-collapse: collapse; text-align: left; font-size: 14px;">
        <thead>
          <tr>
            <th style="padding: 8px; border-bottom: 2px solid #ccc;">Section</th>
            <th style="padding: 8px; border-bottom: 2px solid #ccc;">Old Live Site</th>
            <th style="padding: 8px; border-bottom: 2px solid #ccc;">New HTML Prototype</th>
            <th style="padding: 8px; border-bottom: 2px solid #ccc;">Status</th>
          </tr>
        </thead>
        <tbody>
          ${gapsHtml}
        </tbody>
      </table>

      <h3 style="margin-top:40px; border-bottom: 2px solid #eee; padding-bottom: 8px;">UX & Layout Optimization</h3>
      <p style="font-size: 15px; display: flex; align-items: center;">
        Scroll Depth: <strong>${data.scrollDepth.current} scrolls</strong> (HTML Prototype) &rarr; Target: <strong>${data.scrollDepth.target} scrolls</strong> (Swarm Optimized)
        <span class="info-trigger" style="margin-left: 8px;">i
          <span class="tooltip" style="bottom: 150%;">
            <strong>Scroll Depth Calculation</strong><br>
            • <strong>Prototype:</strong> Calculated from the sections in the provided HTML file.<br>
            • <strong>Target:</strong> Swarm's ideal 4-6 viewport target after applying UI optimization patterns (e.g. tabs).
          </span>
        </span>
      </p>
      ${wireframesHtml}

      <h3 style="margin-top:40px; border-bottom: 2px solid #eee; padding-bottom: 8px;">Action Items</h3>
      <ul style="line-height: 1.6;">
        ${data.actionItems.map(item => `<li><strong>[${item.priority}]</strong> ${item.task}</li>`).join('')}
      </ul>
      <p style="margin-top: 20px; font-style: italic; color: #666;">Want to apply these fixes? Go to Antigravity and say: "Run the Builder agent for ELP"</p>
    `;
    modal.classList.add('active');
  }

  closeBtn.addEventListener('click', () => {
    modal.classList.remove('active');
  });

  window.addEventListener('click', (e) => {
    if (e.target === modal) modal.classList.remove('active');
  });
});
